<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT *
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [4]:
# prompt: how to see table names in database

%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [5]:
%%sql

SELECT *
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [6]:
%%sql

SELECT *
FROM currencyexchange
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [7]:
%%sql
SELECT *
FROM information_schema.columns
WHERE table_name='customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [8]:
%%sql

SELECT *
FROM date
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

In [9]:
%%sql
SELECT
  s.orderdate,
  s.quantity*s.netprice*s.exchangerate as net_revenue,
  c.givenname,
  c.surname,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity*s.netprice*s.exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS high_low
FROM
  sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  orderdate::date >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,336.08,Freda,Howard,North America,1360,Contoso In front of Centrex L15 White,Cell phones,Home & Office Phones,LOW
1,2020-01-01,475.58,Freda,Howard,North America,8,Contoso 4G MP3 Player E400 Silver,Audio,MP4&MP3,LOW
2,2020-01-01,912.21,Robert,Looney,North America,115,WWI Wireless Transmitter and Bluetooth Headpho...,Audio,Bluetooth Headphones,LOW
3,2020-01-01,152.45,Robert,Looney,North America,1756,MGS Age of Empires II Gold Edition E122,Games and Toys,Download Games,LOW
4,2020-01-01,56.02,Swen,Saenger,Europe,1584,SV DVD 38 DVD Storage Binder E25 Black,"Music, Movies and Audio Books",Movie DVD,LOW
...,...,...,...,...,...,...,...,...,...,...
124446,2024-04-19,459.00,James,Bachmann,North America,628,WWI Screen 125in M1611 White,Computers,Projectors & Screens,LOW
124447,2024-04-19,402.84,James,Bachmann,North America,1642,Contoso DVD External DVD Burner M200 Black,"Music, Movies and Audio Books",Movie DVD,LOW
124448,2024-04-19,87.62,Elsie,Cook,North America,1402,Contoso Expandable 4-Handset Cordless Phone Sy...,Cell phones,Home & Office Phones,LOW
124449,2024-04-19,563.16,Elsie,Cook,North America,1611,SV DVD 9-Inch Player Portable M300 White,"Music, Movies and Audio Books",Movie DVD,LOW
124450,2024-04-19,2159.20,Elsie,Cook,North America,454,WWI Desktop PC1.80 E1801 Brown,Computers,Desktops,HIGH

In [24]:
%%sql

/* Total number of customers per order date*/
SELECT
  s.orderdate,
  COUNT(DISTINCT s.customerkey) as total_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS eu_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) AS na_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END) AS au_customers
FROM
  sales s
LEFT JOIN customer c ON s.customerkey=c.customerkey
WHERE
  s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_customers  na_customers  au_customers
0    2023-01-01               12             6             5             1
1    2023-01-02               49            15            31             3
2    2023-01-03               64            17            44             3
3    2023-01-04               78            28            46             4
4    2023-01-05               87            22            57             8
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26            41             6
360  2023-12-28               75            24            44             7
361  2023-12-29               55            19            32             4
362  2023-12-30               91            25            50            16
363  2023-12-31                9             1             8             0

[364 rows x 5 columns]

In [37]:
%%sql
/* Total revenue for year 2022 & 2023*/
SELECT
  p.categoryname,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE 0 END) AS total_net_revenue_2022,
  SUM(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE 0 END) AS total_net_revenue_2023
FROM
  sales s
LEFT JOIN product p ON s.productkey=p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

In [40]:
%%sql
/* Avg, Min, Max revenue for year 2022 & 2023*/
SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE 0 END) AS avg_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE 0 END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE NULL END) AS min_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE NULL END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE NULL END) AS max_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity*s.netprice*s.exchangerate ELSE NULL END) AS max_net_revenue_2023
FROM
  sales s
LEFT JOIN product p ON s.productkey=p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2022,min_net_revenue_2023,max_net_revenue_2022,max_net_revenue_2023
0,Audio,50.18,45.06,9.31,10.85,3473.36,2730.87
1,Cameras and camcorders,176.85,147.23,6.74,5.98,15008.39,13572.00
2,Cell phones,194.66,143.89,2.53,2.28,7692.37,8912.22
3,Computers,384.13,250.55,0.83,0.75,38082.66,27611.60
4,Games and Toys,15.60,13.34,2.83,3.49,5202.01,3357.30
5,Home Appliances,390.05,349.20,4.04,4.54,31654.55,32915.59
6,"Music, Movies and Audio Books",93.37,68.11,7.29,6.91,5415.19,3804.91
7,TV and Video,425.35,322.72,41.30,42.30,30259.41,27503.12

In [66]:
%%sql

/* Median Value categorywise for year 2022 & 2023 */
SELECT
  p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.netprice*s.quantity*s.exchangerate END)) AS year_22_netprice,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.netprice*s.quantity*s.exchangerate END)) AS year_23_netprice
FROM
  sales s
LEFT JOIN
  product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
 p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  year_22_netprice  year_23_netprice
0                          Audio            257.21            266.59
1        Cameras and camcorders             651.46            672.60
2                    Cell phones            418.60            375.88
3                      Computers            809.70            657.18
4                 Games and Toys             33.78             32.62
5                Home Appliances            791.00            825.25
6  Music, Movies and Audio Books            186.58            159.63
7                   TV and Video            730.46            790.79

In [70]:
%%sql
/* Order type categorization */
SELECT orderdate, quantity, netprice,
  CASE
    WHEN quantity>=2 AND netprice>=100 THEN 'Multiple HIGH Value Items'
    WHEN quantity=1 AND netprice>=100 THEN 'Single HIGH Value Items'
    WHEN quantity>=2 AND netprice<100 THEN 'Multiple Standard Items'
    ELSE 'Single Standard Item'
  END AS order_type
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  quantity  netprice                 order_type
0       2015-01-01         1     98.97       Single Standard Item
1       2015-01-01         1    659.78    Single HIGH Value Items
2       2015-01-01         2     54.38    Multiple Standard Items
3       2015-01-01         4    286.69  Multiple HIGH Value Items
4       2015-01-01         7    135.75  Multiple HIGH Value Items
...            ...       ...       ...                        ...
199868  2024-04-20         7    139.19  Multiple HIGH Value Items
199869  2024-04-20         1    159.99    Single HIGH Value Items
199870  2024-04-20         2     53.67    Multiple Standard Items
199871  2024-04-20         5    293.40  Multiple HIGH Value Items
199872  2024-04-20         6      6.88    Multiple Standard Items

[199873 rows x 4 columns]

In [72]:
%%sql
/* Median revenue value for year 2022-23 */
SELECT
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY quantity*netprice*exchangerate) Median
FROM sales
WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [85]:
%%sql

WITH median_value AS (
    SELECT
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY quantity*netprice*exchangerate) AS median
  FROM
    sales
  WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

/*Categorywise low revenue & high revenue  yearwise for 2022-23 */
SELECT p.categoryname,
      SUM(CASE WHEN ((s.quantity * s.netprice * s.exchangerate) < mv.median ) AND
                     (s.orderdate BETWEEN '2022-01-01' AND '2022-12-31')
            THEN (s.quantity * s.netprice * s.exchangerate) END) as Low_Revenue_2022,
      SUM(CASE WHEN ((s.quantity * s.netprice * s.exchangerate) >= mv.median) AND
                    (s.orderdate BETWEEN '2022-01-01' AND '2022-12-31')
            THEN (s.quantity * s.netprice * s.exchangerate) END) as High_Revenue_2022,
      SUM(CASE WHEN ((s.quantity * s.netprice * s.exchangerate) < mv.median ) AND
                    (s.orderdate BETWEEN '2023-01-01' AND '2023-12-31')
            THEN (s.quantity * s.netprice * s.exchangerate) END) as Low_Revenue_2023,
      SUM(CASE WHEN ((s.quantity * s.netprice * s.exchangerate) >= mv.median) AND
                    (s.orderdate BETWEEN '2023-01-01' AND '2023-12-31')
            THEN (s.quantity * s.netprice * s.exchangerate) END) as High_Revenue_2023
FROM sales s
 LEFT JOIN product p ON s.productkey = p.productkey,
 median_value as mv
GROUP BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,low_revenue_2022,high_revenue_2022,low_revenue_2023,high_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cell phones,814449.53,7305215.55,729699.39,5272448.24
2,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
3,TV and Video,272338.29,5542998.32,164275.35,4247902.87
4,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
5,Games and Toys,231979.63,84147.67,206103.36,64271.60
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,Computers,624340.42,17237873.07,590790.31,11060076.90

In [101]:
%%sql
WITH percentiles as (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY quantity*netprice*exchangerate) AS revenue_25th_percentile,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY quantity*netprice*exchangerate) AS median,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY quantity*netprice*exchangerate) AS revenue_75th_percentile
  FROM
    sales
  WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT p.categoryname,
  CASE WHEN ((s.quantity*s.netprice*s.exchangerate)< pctl.revenue_25th_percentile) THEN '3-Low'
       WHEN ((s.quantity*s.netprice*s.exchangerate) BETWEEN pctl.revenue_25th_percentile AND pctl.revenue_75th_percentile) THEN '2-Medium'
       ELSE '1-High'
  END  AS revenue_tier,
  SUM(s.quantity*s.netprice*s.exchangerate) as total_tier_revenue
FROM sales s
 LEFT JOIN product p ON s.productkey = p.productkey,
 percentiles as pctl
GROUP BY p.categoryname, revenue_tier
ORDER BY p.categoryname, revenue_tier

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                     categoryname revenue_tier  total_tier_revenue
0                           Audio       1-High          1213265.71
1                           Audio     2-Medium          3832415.38
2                           Audio        3-Low           267217.01
3         Cameras and camcorders        1-High         15050781.63
4         Cameras and camcorders      2-Medium          3388546.10
5         Cameras and camcorders         3-Low            81032.92
6                     Cell phones       1-High         21874993.15
7                     Cell phones     2-Medium         10338963.22
8                     Cell phones        3-Low           410309.35
9                       Computers       1-High         79607760.89
10                      Computers     2-Medium         10808054.11
11                      Computers        3-Low           203207.06
12                 Games and Toys       1-High           133749.09
13                 Games and Toys     2-Medium          1001381.91
14                 Games and Toys        3-Low           533443.13
15                Home Appliances       1-High         22383475.30
16                Home Appliances     2-Medium          4118724.64
17                Home Appliances        3-Low           105045.60
18  Music, Movies and Audio Books       1-High          3844996.29
19  Music, Movies and Audio Books     2-Medium          6100817.99
20  Music, Movies and Audio Books        3-Low           642496.71
21                   TV and Video       1-High         16632856.33
22                   TV and Video     2-Medium          3766783.30
23                   TV and Video        3-Low            67221.76